name: Periodic health check

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-crimson-surf-2133.fly.dev/health
      - name: Notify Discord success
        if: ${{ success() }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "username": "GitHub Actions Pipeline",
                "avatar_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
                "embeds": [
                  {
                    "title": "Periodic health check passed for Pokedex",
                    "color": 65280,
                    "footer": {
                      "text": "Severity: Informational"
                    }
                  }
                ]
              }' \
            ${{ secrets.DISCORD_WEBHOOK }}
      - name: Notify Discord failure
        if: ${{ failure() }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "username": "GitHub Actions Pipeline",
                "avatar_url": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
                "embeds": [
                  {
                    "title": "Periodic health check failed for Pokedex",
                    "color": 16711680,
                    "footer": {
                      "text": "Severity: Error"
                    }
                  }
                ]
              }' \
            ${{ secrets.DISCORD_WEBHOOK }}
